import {clients,getDemoReport,parseClientId} from "../lib/demo-data";
import {parseRange,percentChange} from "../lib/report";
import {SpendChart} from "../components/spend-chart";
const money=(n:number|null)=>n===null?"Sin datos":new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(n);
const number=(n:number|null)=>n===null?"Sin datos":n.toLocaleString("es-AR",{maximumFractionDigits:0});
const percent=(n:number|null)=>n===null?"Sin datos":n.toLocaleString("es-AR",{maximumFractionDigits:2})+" %";
const link=(client:string,range:number)=>"/?client="+encodeURIComponent(client)+"&range="+range;
function Tile({label,value,change}:{label:string,value:string,change:number|null}){return <article className="tile"><span>{label}</span><strong>{value}</strong><small>{change===null?"Sin período comparable":(change>0?"+":"")+percent(change)+" vs. período anterior"}</small></article>}
export default async function Page({searchParams}:{searchParams:Promise<{client?:string;range?:string}>}){
const p=await searchParams;const client=parseClientId(p.client),range=parseRange(p.range),report=getDemoReport(client,range),t=report.totals,b=report.previousTotals;
return <div className="shell"><aside className="sidebar"><a href="/" className="logo">i<span>.</span> informeta</a><p className="brand-caption">BY FANGER DESIGN</p><div className="sidebar-label">WORKSPACE</div><div className="workspace">◈　Fanger Design</div><div className="sidebar-label">NAVEGACIÓN</div><a className="nav current" href={link(client,range)}>▦　Resumen general</a><div className="nav inactive">▤　Informes　· Próximamente</div><div className="nav inactive">◎　Conexiones　· Próximamente</div><div className="sidebar-foot"><b>● MODO DEMOSTRACIÓN</b><p>No hay cuentas publicitarias conectadas. Todas las métricas son ficticias.</p><small>InforMeta v0.1.0</small></div></aside>
<main className="main"><header className="top"><span>Fanger Design / Analytics / <b>Overview</b></span><span className="demo-status">● Entorno demo</span></header><div className="content"><div className="eyebrow">RENDIMIENTO PUBLICITARIO　✦</div><h1>Resumen general<span className="accent">.</span></h1><p className="subtitle">Todo lo que importa de tus campañas, en un solo lugar.</p>
<div className="warning"><b>ⓘ　Estás viendo datos de demostración</b><p>Los resultados son sintéticos y no provienen de Meta Ads. La integración real se realizará en una fase posterior.</p></div>
<div className="filters"><div><small>CLIENTE</small><div className="buttons">{clients.map(c=><a key={c.id} className={client===c.id?"selected":""} href={link(c.id,range)}>{c.name}</a>)}</div></div><div><small>PERÍODO</small><div className="buttons">{([7,30] as const).map(n=><a key={n} className={range===n?"selected":""} href={link(client,n)}>{n} días</a>)}</div></div></div>
<div className="section-head"><div><h2>Indicadores clave</h2><p>{clients.find(c=>c.id===client)?.name} · {report.startDate} al {report.endDate}</p></div><span className="tag">META ADS · DEMO</span></div>
<div className="metrics"><Tile label="Inversión total" value={money(t.spend)} change={percentChange(t.spend,b.spend)}/><Tile label="Contactos" value={number(t.leads)} change={percentChange(t.leads,b.leads)}/><Tile label="Costo por contacto" value={money(t.cpl)} change={percentChange(t.cpl,b.cpl)}/><Tile label="CTR" value={percent(t.ctr)} change={percentChange(t.ctr,b.ctr)}/></div>
<div className="details"><section className="panel"><h2>Inversión diaria</h2><p>Distribución del presupuesto en el período</p><SpendChart daily={report.daily} currency={report.currency}/></section><section className="panel"><h2>Alcance e interacción</h2><p>Volumen y eficiencia</p><dl>{[["Impresiones",number(t.impressions)],["Clics",number(t.clicks)],["Costo por clic",money(t.cpc)],["CPM",money(t.cpm)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section></div>
<section className="panel campaigns"><div className="section-head"><div><h2>Campañas del período</h2><p>Desglose por campaña · datos de ejemplo</p></div><a href={"/api/reports?client="+client+"&range="+range}>Ver API JSON ↗</a></div><div className="table-wrap"><table><thead><tr><th>Campaña</th><th>Inversión</th><th>Impresiones</th><th>Clics</th><th>Contactos</th><th>CPL</th></tr></thead><tbody>{report.campaigns.map(c=><tr key={c.id}><th>🟢 {c.name}<small>{c.id}</small></th><td>{money(c.totals.spend)}</td><td>{number(c.totals.impressions)}</td><td>{number(c.totals.clicks)}</td><td>{number(c.totals.leads)}</td><td>{money(c.totals.cpl)}</td></tr>)}</tbody></table></div></section><footer>© 2026 Fanger Design · InforMeta MVP · Sin acceso a datos reales</footer></div></main></div>;
}